version: '3.8'

services:
  backend:
    build: .
    container_name: translator-tts-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - argos_models:/root/.local/share/argos-translate
      - kokoro_models:/root/.cache/kokoro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  argos_models:
  kokoro_models:
